### ISSUE TITLE
Disable windows system hibernation while there are players online

### ISSUE THREAD

**Issue by methanoid** [gekigek99/minecraft-vanilla-server-hibernation#10]
I may have totally misunderstood but this "just" sleeps and wakes the server on an active machine?

I'd like to Sleep/Hibernate/Shutdown the Windows PC when nobody on server (and machine inactive also) and to use Wake on LAN to wake the machine and resume server.

Use case: 2nd PC I sometimes use... so don't want it suddenly sleeping when I am actually using it (which Windows itself takes care of, or MacOS or Linux if I were to use them). So I need it to pass the decision as to when to sleep to the OS when the MC server is inactive and on resume (someone remotely WOL's the PC) the MC server needs to resume....

Does that make any sense?!?

**Comment by gekigek99** [comment]
what you are suggesting would be great but unfortunately I think it's practically impossible: WOL use it's own socket type and it's implemented at the level of the motherboard; no program is running when the pc is in hibernation mode so my program won't be able to receive any incoming connection.

One thing you could do is add this line at the end of the stop_empty_minecraft_server function:
`os.system('shutdown /h')`
so that when the minecraft server is shutted down the pc goes in hibernation mode.
This has 2 problems:
1.  It could send the pc in hibernation when you are using it
2.  you have to manually wake up the pc either by WOL or by pressing the power button

I know it's not really a solution but there is no way (that I am aware of) for my program to understand if a user is using the pc (but maybe there is a way, I am not sure) or to wake up the pc from hibernation (for this I am completely sure because the waking up is managed at the motherboard level)

**Comment by methanoid** [comment]
I'm sure I did all this some years ago but memory fails me exactly.. but if you server hibernation really makes the machine inactive so that sleep or hibernate can be triggered (and Minecraft with an active server is enough to STOP sleep or hibernate) then if nobody is using the PC then after 15 mins (or whatever Power Plan is set to) the machine will Sleep or Hibernate and when my user visits a web page to activate Wake On Lan it resumes and your script can resume the active Minecraft server. 

All hinges on whether an active Minecraft server STOPS sleep and an inactive one ALLOWS sleep?

**Comment by gekigek99** [comment]
what do you mean by "visiting a web page to activate Wake On Lan"?

`All hinges on whether an active Minecraft server STOPS sleep and an inactive one ALLOWS sleep?`
well I never considered that option but It should be possible to do something like that.
RIght now i don't have that much time to work on that tho.

Following this link instructions it should be very symple: [look here](https://trialstravails.blogspot.com/2017/03/preventing-windows-os-from-sleeping.html)

I may be able to do that in the next months but if you can script such a thing don't hesitate to create a new file with this option so you can become a contributor. (since implementing such a solution will make the new file work only on windows you can create a new file that we can call windows version)

**Comment by methanoid** [comment]
Hi, thanks.. I've been giving this lots of thought (but my coding skills are rudimentary at best!).

Looks to me like code in Link #1 is most relevant to add this functionality

It just needs a "while player count > 0, do {keep machine from sleeping} " inserting

Then if count gets to zero, it sleeps MC server and machine itself can sleep according to power profiles

If a remote player uses a WOL script to wake server, it resumes you script running and allows them to connect. Then player count becomes 1 and your script resumes keeping machine from sleeping.

However, if the owner of machine wants to use it when no players are online, they can use PC as normal.

**Comment by gekigek99** [comment]
`while player count > 0` is equal to `if player count == 0 then stop the server` which is present in the script (in the stop function).
I think you could try to add simply `osSleep.inhibit()` at the end of the start function and `osSleep.uninhibit()` at the end of the stop function. (obviously you have to ctrl-c/v the class in the example)
therefore when the server has started, windows won't go to sleep and when the stop command is issued, windows will be able to go sleep (after the time sepecified in windows configuration)
#### I would do some experiments with this inhibitor class before implementing it in the script since I know that this kind of things do not work first try ahahahah ;)

The only issue here is that when the server is stopped and windows is in sleep mode the server must be "manually" waked on lan but for what I understand is not a problem for your situation (for me it would be since my server is far away from me)
plus you can also wake the pc by moving the mouse so the possibility of using the server as personal computer is maintained.

**Comment by gekigek99** [comment]
Still consider the option of the `os.system("Powercfg -H OFF")` and `os.system("Powercfg -H ON")` since it makes use of windows commands without having to rely on modifying the registry (which can be: dangerous, tricky and update sensible while Powercfg -H ON is a program done by windows that should work every time... plus you do not have to write a damn new class ahahah)

**Comment by gekigek99** [comment]
this command instead just set windows to sleep without hibernation: `rundll32.exe powrprof.dll,SetSuspendState 0,1,0 `

**Comment by methanoid** [comment]
I dont use Hibernate but actually it might be as "simple" for me as a Python script that just does

"while player count == 0 then osSleep.inhibit() else osSleep.uninhibit()"

I will ask my son if he can grab the count from your script and mash with the suggested code link you gave me!

**Comment by gekigek99** [comment]
yea sure just remember that 
`osSleep.inhibit()`      --> pc does NOT sleep
`osSleep.uninhibit()`  --> pc is allowed to sleep

Since i want to be as helpful as I can here is a possible implementation:
this is what you want: [code](https://hatebin.com/ilcehjadpj)
this is a simpler version in my opinion (almost guaranteed to work): [code](https://hatebin.com/eshoalihlh)

If this issue helped you please consider starring my repository and having a cup of coffee with me [here](https://www.buymeacoffee.com/gekigek99)

I am still available for help if needed
