### ISSUE TITLE
No error messages / output on Ubuntu and File path specifications

### ISSUE THREAD

**Issue by GavvyDizzle** [gekigek99/minecraft-vanilla-server-hibernation#6]
I'm new to Ubuntu so I set up a VM on my computer before making my server run on it. I'm having some trouble getting the script work properly and I don't know what's wrong because there is no output to the terminal. It is likely because I incorrectly put in the server path. It is located in my home directory with all my other server files in a folder called minecraftdir. I am using the line "/home/gavvydizzle/minecraft" to reference the server folder. Just to add, I am using the terminal to run the python3 script. Is my directory wrong? or am I running the script incorrectly? Thanks for your help in advance. Edit: This was occuring on version 2.0 of the script

**Comment by gekigek99** [comment]
ok first of all download the most recent version (mainly because i updated it 30 min ago lol and it works much better)

what operative system are you using?
what vm are you using? virtualbox, vmware or others? (i find vmware to work much better for me, it integrates much better with windows)

let's debug a little:

if you try to launch the server manually with 
`java -Xmx1024M -Xms1024M -jar /home/gavvydizzle/minecraft/server.jar nogui`
does it launches the server?
can you access it from your minecraft client? (remember: since you are launching directly the server you should access it from port 25565)

***remember to open port 25565 (in this case) on the ubuntu server (and if you are trying to access from an other computer on the same LAN open also port 25565 in the firewall of your host OS)

**Comment by gekigek99** [comment]
***remember to rename "minecraft_server.jar" (in the script) to the actual name of your server file

**Comment by GavvyDizzle** [comment]
Yea I got it working quickly after downloading the newest version, I was using Hyper-V

**Comment by gekigek99** [comment]
ok so now it's problem solved?

**Comment by gekigek99** [comment]
if yes, there is a good chance it was working also before but the script just didn't print anything when it was listening (it would print something only when a player connected)
