### ISSUE TITLE
Hibernation applyed on multiple servers for pterodactyl panel

### ISSUE THREAD

**Issue by Ho2x** [gekigek99/minecraft-vanilla-server-hibernation#7]
Hello,
are you able to write the same code in javascript for the pterodactyl panel?

If yes I can even pay you for this.

thank you

**Comment by gekigek99** [comment]
Yea sure I may be able to help you but i need a little more info!

Why do you need specifically javascript?
How are you trying to integrate this script in the pterodactyl panel?
What is your general situation? (what games are we talking about? how many? is it all on one machine?)
Do you want to use pterodactyl because it uses Docker so the start and stop of the server is immediate?

just to make an idea of your specific case... mybe we can make it work without having to rewrite the entire pterodactyl repo... 👍

**Comment by gekigek99** [comment]
Do you need to visualize remotely with a browser all the servers running or you just need to run multiple game servers on the same machine?

**Comment by Ho2x** [comment]
Hello,
Thank you for your positive response.
So for a little summary.
I am busy redoing the administration of my servers with the pterodactyl panel.
I currently have two centos 7 servers.
Indeed pterodactyl uses docker and Javascript well.
I don't know more than that.
I would like all minecraft servers to be automatically, when creating the server, with a hibernation system.
Kind of like the McMyAdmin panel suggests.

Thank you for your time and your work.

**Comment by Ho2x** [comment]
Yes, I use the browser to manage all the servers (pterodactyl panel) if your code can be executed when creating a new server this would be perfect. An option for the user seems to me to be too complicated (enable-disable sleep mod)
But if I already know how to force minecraft vanilla or mod servers to have a system like McMyAdmin. This would save me a lot of cpu and ram resource for servers with zero players.

**Comment by gekigek99** [comment]
i could write an external program that launches automatically the docker server (and i would write some config file so that it is easy to add each docker id in a simple manner)
if you run from terminal:
`docker run -i -t <image-id> /bin/bash`
you should find the image-id in "server configuration" with the variable name: "UUID / Docker Container ID"

and while keeping it running you check the panel, does it shows as running?

**Comment by Ho2x** [comment]
Indeed, it seems to stay online

**Comment by gekigek99** [comment]
yea i mean...
- from the browser set the minecraft server offline
- then run the command via ssh or terminal
- finally check if on the browser the minecraft server is shown as launched (and everything looks as normal)

if it works i can find a workaround that can work even if pterodactyl gets updated/changed

**Comment by gekigek99** [comment]
Ok I have found a solution for this problem.

I will write something in python completely detached from pterodactyl panel in the next weeks so that it works whatever the pterodactyl version is.

Please contact me on 
gekigek.99@gmail.com
for further informations so that I can close this issue.

**Comment by gekigek99** [comment]
@Ho2x are you still interested?

**Comment by gekigek99** [comment]
@Ho2x if you are still interested i wrote a cool program that does exacly this for pterodactyl

I've uploaded it on mc market and waiting for verification but if you need it I can send it to you

**Comment by gekigek99** [comment]
@Ho2x pterodactyl server hibernation is finally out!

You check it out [here](https://www.mc-market.org/resources/16663/)!!!
