### ISSUE TITLE
Error codes showing but the program is still executing

### ISSUE THREAD

**Issue by GavvyDizzle** [gekigek99/minecraft-vanilla-server-hibernation#8]
I've been running the 4.0 Version of the vanilla server hibernation script for about 2-3 weeks with no problems. Tonight I restarted my Ubuntu machine to come back to the error "OSError: [Errno 98] Address already in use." I'm not sure that this error entails so I'm asking here. The weird thing is that despite this error message, players can still join my server. Any suggestions or fixes? Thanks. I attached the error in the terminal window
![image](https://user-images.githubusercontent.com/57154434/78203726-b5de8700-7465-11ea-872f-e32ba624a808.png)

**Comment by gekigek99** [comment]
you probably have the m-v-s-h.py already running. Did you set up a service to restart at reboot?
Because it looks like the program has already binded the host:port and a 2 program can't bind it anymore.

use this: `sudo netstat -ntlp | grep LISTEN` to see what program are using which port. You probably will find that you have m-v-s-h.py already running.
To visualize better the process you can use `htop` and look for the pid you found with the above command. (from htop you can kill the process -> after you killed it you shuld be able to launch it from terminal as you tried in the picture)

**Comment by GavvyDizzle** [comment]
Yes, it was already running. Thanks for the help, everything is running fine.
